name: Auto Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Capture CHANGELOG.md content
        run: |
          {
            echo 'CHANGELOG_CONTENT<<EOF'
            awk '
            /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/ {
                if (in_block) {exit}
                in_block=1; next
            }
            in_block {
                if (/^## \[[0-9]+\.[0-9]+\.[0-9]+\]/) {print buffer; exit}
                buffer = buffer $0 "\n"
            }
            END {
                if (in_block) {print buffer}
            }
            ' CHANGELOG.md
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Generate release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            dist/*.zip
            dist/*.tar.gz
          body: ${{ env.CHANGELOG_CONTENT }}
