name: Nuke Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test and Publish NuGet Package
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build, Test and Publish NuGet Package
        run: |
          chmod +x ./build.sh # Ensure the build script is executable
          ./build.sh --configuration Release --nuget-api-key ${{ secrets.NUGET_API_KEY }} --nuget-source https://api.nuget.org/v3/index.json
